language: java
install: true
jdk: openjdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_script:
  - ./gradlew --version

script:
  - TERM=dumb ./gradlew -S build
